apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-sqs-hpa-controller
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-sqs-hpa-controller
rules:
  - apiGroups: ["autoscaling"]
    resources:
      - "horizontalpodautoscalers"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-sqs-hpa-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-sqs-hpa-controller
subjects:
  - kind: ServiceAccount
    name: k8s-sqs-hpa-controller
    namespace: kube-system
